### ISSUE TITLE
UnhandledPromiseRejectionWarning: URIError: URI malformed

### ISSUE THREAD

**Issue by cemremengu** [vercel/serve#470]
I regularly keep getting this error from time to time when serving my react app with

`serve -s app.js`

Is this a bug or there is a way to check/prevent this error? 

```
(node:13396) UnhandledPromiseRejectionWarning: URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at module.exports (C:\Users\ttgintcmengu\AppData\Roaming\npm\node_modules\se
rve\node_modules\serve-handler\src\index.js:493:23)
    at Server.http.createServer (C:\Users\ttgintcmengu\AppData\Roaming\npm\node_
modules\serve\bin\serve.js:156:58)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
(node:13396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:13396) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
```

**Comment by leerob** [comment]
Closing as stale 🙏

**Comment by mahmoudafer1** [comment]
version 11.3.2 and still getting this error
