### ISSUE TITLE
An error occurred when the HTML file was in Chinese

### ISSUE THREAD

**Issue by xiaotan0305** [vercel/serve#485]
![image](https://user-images.githubusercontent.com/12965330/47538639-0cee3d00-d8ff-11e8-94d3-c79e0602727f.png)

> The error message is as follows

```
(node:851) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Location"]
    at storeHeader (_http_outgoing.js:411:5)
    at processHeader (_http_outgoing.js:406:3)
    at ServerResponse._storeHeader (_http_outgoing.js:312:9)
    at ServerResponse.writeHead (_http_server.js:270:8)
    at module.exports (/usr/local/lib/node_modules/serve/node_modules/_serve-handler@5.0.3@serve-handler/src/index.js:558:12)
    at Server.http.createServer (/usr/local/lib/node_modules/serve/bin/serve.js:156:58)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:652:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
(node:851) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by leerob** [comment]
This package doesn't currently support this features. I'm open to reviewing a PR if you add support, but for right now, closing this as won't fix 🙏
