### ISSUE TITLE
Error: Cannot find module '../package'

### ISSUE THREAD

**Issue by jshji252** [vercel/serve#689]
Hello,

Thanks for great package!

I am trying to deploy a simple website on Elastic Beanstalk on AWS. And the following error is thrown when it starts the app with `serve -s build` command:
```
Jan 19 10:46:45 ip-172-31-37-45 web: Error: Cannot find module '../package'
Jan 19 10:46:45 ip-172-31-37-45 web: Require stack:
Jan 19 10:46:45 ip-172-31-37-45 web: - /var/app/current/node_modules/.bin/serve
Jan 19 10:46:45 ip-172-31-37-45 web: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
Jan 19 10:46:45 ip-172-31-37-45 web: at Function.Module._load (internal/modules/cjs/loader.js:746:27)
Jan 19 10:46:45 ip-172-31-37-45 web: at Module.require (internal/modules/cjs/loader.js:974:19)
Jan 19 10:46:45 ip-172-31-37-45 web: at require (internal/modules/cjs/helpers.js:93:18)
Jan 19 10:46:45 ip-172-31-37-45 web: at Object.<anonymous> (/var/app/current/node_modules/.bin/serve:24:13)
Jan 19 10:46:45 ip-172-31-37-45 web: at Module._compile (internal/modules/cjs/loader.js:1085:14)
Jan 19 10:46:45 ip-172-31-37-45 web: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Jan 19 10:46:45 ip-172-31-37-45 web: at Module.load (internal/modules/cjs/loader.js:950:32)
Jan 19 10:46:45 ip-172-31-37-45 web: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Jan 19 10:46:45 ip-172-31-37-45 web: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
Jan 19 10:46:45 ip-172-31-37-45 web: code: 'MODULE_NOT_FOUND',
Jan 19 10:46:45 ip-172-31-37-45 web: requireStack: [ '/var/app/current/node_modules/.bin/serve' ]
Jan 19 10:46:45 ip-172-31-37-45 web: }
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! code ELIFECYCLE
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! errno 1
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! my-blog@0.1.0 serve: `ls -la && serve -s build`
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! Exit status 1
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR!
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! Failed at the my-blog@0.1.0 serve script.
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR! A complete log of this run can be found in:
Jan 19 10:46:45 ip-172-31-37-45 web: npm ERR!     /home/webapp/.npm/_logs/2022-01-19T10_46_45_365Z-debug.log
```

I think it's because in the source code, it's requiring package in line 24: `const pkg = require('../package');` but AWS is using serve source code from `/var/app/current/node_modules/.bin/serve` and the relative directory ` '../package' ` doesn't work in that location? I am not sure.

Any help will be greatly appreciated!! Just for an FYI, it's a very simple react app generated from create react app. I build it, and then serve the build folder using serve.

Thank you!

**Comment by jshji252** [comment]
I wanted to see if that actually was the issue, so I cloned the code base and basically just tried to remove wherever it uses the variable `pkg`. Then I published it on to npm using `serve-nopkg`, so that I can test, and it is working fine now.

To properly fix this problem, I think we need a different way to read `package.json` file, or re-structure the codes so that the `serve` file in `node_modules/.bin` folder won't read package.json? I am a junior developer so maybe what I'm saying doesn't make sense at all.

Anyway, thank you for a great npm package :)

**Comment by jshji252** [comment]
I am thinking maybe this problem was caused by my environment. My local machine is Node@16, and elastic beanstalk has node@14. Could it be that the problem was because of using old node version, not Serve itself?

I tried installing node14 on my local machine and ran my project, and it worked fine. so maybe node version wasn't the issue?? I am confused @.@.

**Comment by jshji252** [comment]
And now I see there are other packages also uses relative paths to refer to `package.json`, and also I read that files in .bin are just references to actual directories in `node_modules, so the relative paths should correctly resolve to `package.json`. I'm completely lost why I encountered that error @.@

**Comment by Carsair** [comment]
@jshji252 Did you ever find out what the issue was here?
