### ISSUE TITLE
npx serve --help crashes

### ISSUE THREAD

**Issue by crimsonhawk47** [vercel/serve#731]
When running a freshly installed serve in a project, this happens. 

```
{project-path}/node_modules/serve/build/main.js:427
  await printUpdateNotification(args["--debug"]);
  ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:122:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```

This also happens when using npx serve, though the path to the file is different. 

I am on a windows 10 with node 14.7.0.

**Comment by ibrokemycomputer** [comment]
@crimsonhawk47 If you use serve version 13.0.4 the command works again.

`npm i serve@13.0.4`
